### ISSUE TITLE
Works on WSL?

### ISSUE THREAD

**Issue by kozross** [kouya/snownews#14]
Now that the Windows Subsystem for Linux is a thing, maybe Snownews will run on it? I'd like to have this tested, but I don't use Windows, and thus can't.

**Comment by kouya** [comment]
There is no reason why it should not run. It's a full install of Ubuntu (I think Suse/Fedora too, or soon) with all the tools and libs and it's only a console application. If a django development with database runs, this must work too. So I'm closing this until someone else proves me otherwise or submits a bug against it. :)
